<?
if(!defined('B_PROLOG_INCLUDED') || B_PROLOG_INCLUDED !== true) die();

$indexPageOptions = $GLOBALS['arTheme']['INDEX_TYPE']['SUB_PARAMS'][$GLOBALS['arTheme']['INDEX_TYPE']['VALUE']];
$blockOptions = $indexPageOptions['TARIFFS'];
$blockTemplateOptions = $blockOptions['TEMPLATE']['LIST'][$blockOptions['TEMPLATE']['VALUE']];
$bTariffsUseDetail = $GLOBALS['arTheme']['TARIFFS_USE_DETAIL']['VALUE'] === 'Y';
$defaultPriceKey = $GLOBALS['arTheme']['TARIFFS_DEFAULT_PRICE_KEY']['VALUE'] ?? 'DEFAULT';
$defaultItemName = $GLOBALS['arTheme']['TARIFFS_DEFAULT_ITEM_NAME']['VALUE'] ?? '';
$defaultFallback = $GLOBALS['arTheme']['TARIFFS_DEFAULT_FALLBACK']['VALUE'] ?? '';

$tabs = $blockOptions["INDEX_BLOCK_OPTIONS"]["BOTTOM"]["TABS"]["VALUE"];
if ($tabs === 'TOP') {
	$iblockId = TSolution\Cache::$arIBlocks[SITE_ID]['aspro_allcorp3_catalog']['aspro_allcorp3_tarifs'][0];
	$defaultPriceKey = $defaultItemName = TSolution\Property\TariffItem::mkTabFilter($iblockId, 'arFrontFilter');
}
?>
<?$APPLICATION->IncludeComponent(
	"bitrix:news.list", 
	"tariffs-list", 
	[
		"IBLOCK_TYPE" => "aspro_allcorp3_catalog",
		"IBLOCK_ID" => "35",
		"NEWS_COUNT" => "4",
		"SORT_BY1" => "SORT",
		"SORT_ORDER1" => "ASC",
		"SORT_BY2" => "ID",
		"SORT_ORDER2" => "DESC",
		"FILTER_NAME" => "arFrontFilter",
		"FIELD_CODE" => [
			0 => "NAME",
			1 => "PREVIEW_TEXT",
			2 => "PREVIEW_PICTURE",
			3 => "",
		],
		"PROPERTY_CODE" => [
			0 => "FORM_ORDER",
			1 => "HIT",
			2 => "PRICE_CURRENCY",
			3 => "TARIF_PRICE_1",
			4 => "TARIF_PRICE_2",
			5 => "TARIF_PRICE_2_DISC",
			6 => "TARIF_PRICE_3",
			7 => "TARIF_PRICE_3_DISC",
			8 => "TARIF_PRICE_DEFAULT",
			9 => "TARIF_PRICE_DEFAULT_DISC",
			10 => "TARIF_ITEM",
			11 => "MULTI_PROP",
			12 => "SUPPLIED",
			13 => "USERS",
			14 => "EXTENSION",
			15 => "DURATION",
			16 => "GROUPS_USERS",
			17 => "ADMIN",
			18 => "VOLUME",
			19 => "FILE_STORAGE",
			20 => "MEMORY",
			21 => "CPU",
			22 => "IP",
			23 => "HOSTING_SITES",
			24 => "KOLLICHESTVO_BAZ_DANNIX",
			25 => "ONLY_ONE_PRICE",
			26 => "MULTI_PROP_BOTTOM_PROPS",
			27 => "TASK",
			28 => "ONLINE",
			29 => "MESSAGE",
			30 => "UPDATES",
			31 => "LANGUAGES",
			32 => "TARIF_PRICE_1_DISC",
			33 => "TARIF_PRICE_4",
			34 => "ICON",
			35 => "VISA",
			36 => "NUM_DEVICES",
			37 => "APPLE",
			38 => "ELPURSE",
			39 => "API_INTEGRATION",
			40 => "SIEM_SYSTEM",
			41 => "COLLECT_INFO",
			42 => "RULES_SIGNAT",
			43 => "SCANNER",
			44 => "ANTIVIRUS",
			45 => "PROTECT_PAYMENT",
			46 => "PROTECT_CAMERA",
			47 => "ANTIVOR",
			48 => "CONTROL",
			49 => "SUPPORT_FREE",
			50 => "GUARANTEE",
			51 => "BLOCKING_SITES",
			52 => "BLOCKING_TRAFFIC",
			53 => "SECURITY",
			54 => "PROTECT_CHILDREN",
			55 => "SUM_FINANCING",
			56 => "TERM_LEASING",
			57 => "INSURANCE",
			58 => "CURRENCY",
			59 => "ADVANCE_PAY",
			60 => "RATE",
			61 => "PERCENTAGE",
			62 => "PAYMENTS",
			63 => "SUPPORT",
			64 => "NOTIFICATION",
			65 => "TURN",
			66 => "",
		],
		"CHECK_DATES" => "Y",
		"DETAIL_URL" => "",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "3600000",
		"CACHE_FILTER" => "Y",
		"CACHE_GROUPS" => "N",
		"PREVIEW_TRUNCATE_LEN" => "",
		"ACTIVE_DATE_FORMAT" => "j F Y",
		"SET_TITLE" => "N",
		"SET_STATUS_404" => "N",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"ADD_SECTIONS_CHAIN" => "N",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"PARENT_SECTION" => "",
		"PARENT_SECTION_CODE" => "",
		"INCLUDE_SUBSECTIONS" => "Y",
		"PAGER_TEMPLATE" => "ajax",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => "",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "3600000",
		"PAGER_SHOW_ALL" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"SET_BROWSER_TITLE" => "N",
		"SET_META_KEYWORDS" => "N",
		"SET_META_DESCRIPTION" => "N",
		"COMPONENT_TEMPLATE" => "tariffs-list",
		"SET_LAST_MODIFIED" => "N",
		"STRICT_SECTION_CHECK" => "Y",
		"SHOW_DETAIL_LINK" => "Y",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"SHOW_404" => "N",
		"MESSAGE_404" => "",
		"SHOW_DATE" => "N",
		"COUNT_IN_LINE" => "1",
		"USE_DETAIL" => $bTariffsUseDetail?"Y":"N",
		"VISIBLE_PROP_COUNT" => "4",
		"ROW_VIEW" => true,
		"BORDER" => true,
		"ITEM_HOVER_SHADOW" => true,
		"DARK_HOVER" => false,
		"ROUNDED" => true,
		"ROUNDED_IMAGE" => false,
		"ELEMENTS_ROW" => "1",
		"MAXWIDTH_WRAP" => true,
		"MOBILE_SCROLLED" => true,
		"HIDE_PAGINATION" => "N",
		"SLIDER" => false,
		"VIEW_TYPE" => "type_3",
		"ORDER_VIEW" => CAllcorp3::GetFrontParametrValue("ORDER_VIEW")=="Y",
		"NARROW" => $blockTemplateOptions["ADDITIONAL_OPTIONS"]["WIDE"]["VALUE"]!="Y",
		"ITEMS_OFFSET" => $blockTemplateOptions["ADDITIONAL_OPTIONS"]["ITEMS_OFFSET"]["VALUE"]=="Y",
		"IMAGES" => $blockTemplateOptions["ADDITIONAL_OPTIONS"]["IMAGES"]["VALUE"],
		"HIDE_LEFT_TEXT_BLOCK" => "Y",
		"TABS" => $tabs,
		"DEFAULT_PRICE_KEY" => $defaultPriceKey,
		"DEFAULT_ITEM_NAME" => $defaultItemName,
		"DEFAULT_FALLBACK" => $defaultFallback,
		"SHOW_TITLE" => $blockOptions["INDEX_BLOCK_OPTIONS"]["BOTTOM"]["SHOW_TITLE"]["VALUE"]=="Y",
		"TITLE_POSITION" => $blockOptions["INDEX_BLOCK_OPTIONS"]["BOTTOM"]["TITLE_POSITION"]["VALUE"],
		"TITLE" => "Цены на геодезию и кадастр в МСК в 2026 году",
		"RIGHT_TITLE" => $GLOBALS["arTheme"]["TARIFFS_USE_DETAIL"]["VALUE"]==="Y"?"Все тарифы":"",
		"RIGHT_LINK" => $GLOBALS["arTheme"]["TARIFFS_USE_DETAIL"]["VALUE"]==="Y"?"tariffs/":"",
		"CHECK_REQUEST_BLOCK" => CAllcorp3::checkRequestBlock("tariffs"),
		"IS_AJAX" => CAllcorp3::checkAjaxRequest(),
		"NAME_SIZE" => "22",
		"SUBTITLE" => "",
		"SHOW_PREVIEW_TEXT" => "Y",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO"
	],
	false
);?>